name: DragonIRC
version: ${pluginversion}
main: org.fastlizard4.dragonirc.DragonIRC
authors: [FastLizard4, wlritchi]
description: Minecraft chat to IRC bridge
website: https://git.fastlizard4.org/gitblit/summary/?r=craftbukkit-plugins/DragonIRC.git

commands:
  dragonirc:
    description: Reloads the plugin.
    aliases: [dirc]
    usage: /<command>
  ircmessage:
    description: Sends a message to a user on IRC.
    aliases: [im]
    usage: /<command> [server] [user] [message]
  irckick:
    description: Kicks a user from a channel on IRC.
    aliases: [ik]
    usage: /<command> [server] [channel] [user] (reason)
  ircrestartbots:
    description: Restarts all IRC bots.
    aliases: [irb]
    usage: /<command>

permissions:
  dragonirc.*:
    description: Grants all permissions.
    default: false
    children:
      dragonirc.dragonirc: true
      dragonirc.ircmessage: true
      dragonirc.irckick: true
      dragonirc.ircrestartbots: true
  dragonirc.dragonirc:
    description: Allows /dragonirc.
    default: op
  dragonirc.ircmessage:
    description: Allows /ircmessage.
    default: op
  dragonirc.irckick:
    description: Allows /irckick.
    default: op
  dragonirc.ircrestartbots:
    description: Allows /ircrestartbots.
    default: op
